In [56]:
import scipy.io
import numpy as np

data = scipy.io.loadmat('/Users/isaaclee/Wildfire_Research/validation_case_data_and_preparation/validation_case_data.mat')
data = data['data_vec']

np.save('validation_case_data.npy', data)

print(data.shape)
print(data)


(11, 27)
[[1.46718820e+01 4.12357105e+01 9.76066257e+01 0.00000000e+00
  0.00000000e+00 5.65714495e-01 5.53277948e-01 3.71145976e-01
  7.20625516e-01 4.41168048e-01 4.43235604e-01 4.03431836e-01
  4.36635763e-01 3.22222222e-04 5.01222222e-02 0.00000000e+00
  1.78333333e-02 8.79444444e-02 4.66666667e-04 2.44444444e-04
  2.56888889e-02 1.59033333e-01 6.55011111e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.33333333e-03]
 [1.09344131e+02 2.16526091e+02 3.10117254e+02 0.00000000e+00
  0.00000000e+00 5.92223341e-01 4.81091593e-01 3.77819557e-01
  7.09517005e-01 4.41168048e-01 4.43235604e-01 4.03431836e-01
  4.36635763e-01 3.22222222e-04 5.01222222e-02 0.00000000e+00
  1.78333333e-02 8.79444444e-02 4.66666667e-04 2.44444444e-04
  2.56888889e-02 1.59033333e-01 6.55011111e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.33333333e-03]
 [1.26950390e+02 3.18457060e+02 5.29268839e+02 0.00000000e+00
  0.00000000e+00 6.23585039e-01 3.55544100e-01 4.64969562e-01
  6.42989089e-01 4.41168048

In [46]:
data = np.concatenate([np.zeros((data.shape[0],2)), data], axis=1)

In [47]:
print(data.shape[0])

11


In [49]:
data_row = data[1,:]

print(data_row.shape)

data_row = np.tile(data_row, (100, 1))
print(data_row.shape)


(29,)
(100, 29)


In [50]:
array = np.array([0,1,2,3,4])
print(array)
array = array.T
print(array)
print(array.shape)

[0 1 2 3 4]
[0 1 2 3 4]
(5,)


In [58]:
fire_area_matrix = np.load('/Users/isaaclee/Wildfire_Research/validation_case_data_and_preparation/fire_area_matrix.npz')
print(fire_area_matrix['arr_0'])

[[[-1.53328562  1.24727535  0.45380273]
  [-1.14990354 -1.0511452  -2.44018579]
  [-0.90348452 -1.4480406  -2.37868047]
  ...
  [ 3.54545474 -0.51382357  1.17119181]
  [ 0.94977558 -0.76047623 -0.26461673]
  [ 1.22928333 -1.36511469 -0.96444666]]

 [[ 0.7039811  -1.09939122  4.7501955 ]
  [-2.04620886  1.73545504 -1.68037891]
  [-1.050246   -1.63458407  2.31062579]
  ...
  [ 2.32158542 -0.90280861 -1.44384837]
  [ 1.41064739  0.87761366 -1.31453145]
  [ 3.30620098  0.8349793  -1.76621008]]

 [[ 1.16282606  2.09113121 -1.40565169]
  [-0.40847361  0.29781505 -1.53892493]
  [-0.17902273 -0.75329453 -1.98581588]
  ...
  [-0.98737627 -1.85025656 -0.2944282 ]
  [-0.2760942   0.64903283 -0.28904524]
  [-0.03530875  0.98972732  1.03676748]]

 ...

 [[ 1.29370666  1.89705038  3.63332844]
  [ 0.78281969  0.15168935 -0.86792088]
  [-1.04336143  0.33354244 -1.42228794]
  ...
  [-0.33879447  0.20375973  1.27303648]
  [-1.49419856  1.28413081  0.03085874]
  [-0.11208872 -2.25281143 -2.75520158]]

 [